# California District Attorney Project

The data used in this project can be viewed [here](https://drive.google.com/open?id=1lTwNX7moD-4BvAV5Fd5HbqL3luheYGc0).

In [1]:
import pandas as pd
import numpy as np
import logging

In [110]:
# read in the data 
police_violence_df = pd.read_excel('./data/police_violence_2013_18.xlsx', sheet_name='Police_Killings_2013_18')
ca_race_df = pd.read_csv('./data/ca_race.csv')

In [33]:
police_violence_df.head()

,Victim's name,Victim's age,Victim's gender,Victim's race,URL of image of victim,Date of Incident (month/day/year),Street Address of Incident,City,State,Zipcode,...,Criminal Charges?,Link to news article or photo of official document,Symptoms of mental illness?,Unarmed,Alleged Weapon (Source: WaPo),Alleged Threat Level (Source: WaPo),Fleeing (Source: WaPo),Body Camera (Source: WaPo),WaPo ID (If included in WaPo database),Unnamed: 24
0,Name withheld by police,Unknown,Male,Unknown race,NaN,2018-05-18,Southwest Pleasant View and Highland drive,Gresham,OR,NaN,...,No Known Charges,http://www.kxl.com/police-shoot-and-kill-man-i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name withheld by police,Unknown,Male,Unknown race,NaN,2018-05-17,Britton Rd. and Kilpatrick Turnpike,Oklahoma City,OK,NaN,...,No Known Charges,http://kfor.com/2018/05/17/emergency-crews-inv...,NaN,Allegedly Armed,gun,attack,Not fleeing,NaN,NaN,NaN
2,Name withheld by police,Unknown,Male,Unknown race,NaN,2018-05-16,Washington Blvd,Belmont,OH,NaN,...,No Known Charges,http://wtov9.com/news/local/new-details-releas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,David Romansky,34,Male,White,NaN,2018-05-15,NaN,Lake Mary,FL,NaN,...,No Known Charges,http://www.orlandosentinel.com/news/breaking-n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Marcus-David L. Peters,24,Male,Black,http://www.fatalencounters.org/wp-content/uplo...,2018-05-14,I-95 and Chamberlayne Avenue,Richmond,VA,23227.0,...,No Known Charges,http://www.nbc12.com/story/38187605/naked-man-...,No,Unarmed,unarmed,attack,Car,No,3696.0,NaN

In [36]:
ca_race_df.head()

,Geography,total_population,his_latino,his_latino_percent,white,white_percent,black,black_percent,american_native,american_native_percent,...,asian_percent,pac_islander,pac_islander_percent,other,other_percent,two_plus,two_plus_percent,Summary_Level,County,Place
0,California,"38,654,206","14,903,982",38.6,"14,837,242",38.4,"2,158,363",5.6,"136,582",0.4,...,13.7,"138,956",0.4,"90,413",0.2,"1,107,850",2.9,40.0,NaN,NaN
1,Alameda County,"1,605,217","362,070",22.6,"523,797",32.6,"176,819",11.0,"4,959",0.3,...,28.0,"13,223",0.8,"4,524",0.3,"70,149",4.4,50.0,1.0,NaN
2,Alameda city,"77,409","9,123",11.8,"33,269",43.0,"5,742",7.4,135,0.2,...,30.4,550,0.7,413,0.5,"4,625",6.0,160.0,1.0,562.0
3,Albany city,"19,420","2,506",12.9,"9,442",48.6,740,3.8,63,0.3,...,26.4,156,0.8,149,0.8,"1,246",6.4,160.0,1.0,674.0
4,Ashland CDP,"24,288","10,872",44.8,"3,146",13.0,"4,529",18.6,75,0.3,...,19.3,149,0.6,47,0.2,779,3.2,160.0,1.0,2980.0

## CA Police Violence Data

In [119]:
# select for only CA entries
ca_police_violence_df = police_violence_df[police_violence_df['State'] == 'CA']

In [120]:
# remove whitespace and special chars from col names
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace('\s+', '_')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace("'", '')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace('(', '')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace(')', '')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace('?', '')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace('/', '')
ca_police_violence_df.columns = ca_police_violence_df.columns.str.replace(':', '')

In [121]:
# save csv of the ca police violence dataframe 
ca_police_violence_df.to_csv('ca_police_violence.csv', encoding='utf-8', index='false')

In [127]:
# get the per county incidents
ca_counties_df = ca_police_violence_df.County.value_counts()

In [128]:
# reindex the dataframe to include a county column
ca_counties_df = pd.DataFrame(ca_counties_df)
ca_counties_df.reset_index(level=0, inplace=True)
ca_counties_df.columns = ['county', 'police_violence_incidents']

In [129]:
ca_counties_df['county'] = ca_counties_df['county'].astype(str) + ' County'

In [132]:
# add a totals row
total = pd.Series({'county':'California', 'police_violence_incidents': ca_counties_df.police_violence_incidents.sum()})
ca_counties_df = ca_counties_df.append(total, ignore_index=True)

In [133]:
ca_counties_df.head()

                  county  police_violence_incidents
0     Los Angeles County                        283
1       Riverside County                         70
2       San Diego County                         61
3  San Bernardino County                         60
4         Alameda County                         48

## Demographic Data

In [39]:
ca_county_race_df = ca_race_df[(ca_race_df['Geography'].str.contains('County')) | (ca_race_df['Geography'] == 'California')]

In [91]:
# remove census designated places
cdp = ca_county_race_df['Geography'].str.contains("CDP")
ca_county_race_df = ca_county_race_df[~cdp]

In [141]:
ca_county_race_df = ca_county_race_df.rename(columns={'Geography': 'county'})

In [142]:
ca_county_race_df.head()

,county,total_population,his_latino,his_latino_percent,white,white_percent,black,black_percent,american_native,american_native_percent,...,asian_percent,pac_islander,pac_islander_percent,other,other_percent,two_plus,two_plus_percent,Summary_Level,County,Place
0,California,"38,654,206","14,903,982",38.6,"14,837,242",38.4,"2,158,363",5.6,"136,582",0.4,...,13.7,"138,956",0.4,"90,413",0.2,"1,107,850",2.9,40.0,NaN,NaN
1,Alameda County,"1,605,217","362,070",22.6,"523,797",32.6,"176,819",11.0,"4,959",0.3,...,28.0,"13,223",0.8,"4,524",0.3,"70,149",4.4,50.0,1.0,NaN
22,Alpine County,"1,184",92,7.8,804,67.9,10,0.8,224,18.9,...,0.8,0,0.0,0,0.0,45,3.8,50.0,3.0,NaN
28,Amador County,"36,963","4,822",13.0,"29,436",79.6,860,2.3,458,1.2,...,1.4,72,0.2,4,0.0,790,2.1,50.0,5.0,NaN
47,Butte County,"223,877","34,503",15.4,"164,398",73.4,"3,279",1.5,"1,553",0.7,...,4.2,380,0.2,340,0.2,"9,927",4.4,50.0,7.0,NaN

## Merging

In [143]:
# merge the two dataframes
merged_df = ca_counties_df.merge(ca_county_race_df, how='inner', on='county')

In [145]:
merged_df.head()

,county,police_violence_incidents,total_population,his_latino,his_latino_percent,white,white_percent,black,black_percent,american_native,...,asian_percent,pac_islander,pac_islander_percent,other,other_percent,two_plus,two_plus_percent,Summary_Level,County,Place
0,Los Angeles County,283,"10,057,155","4,861,648",48.3,"2,687,787",26.7,"801,182",8.0,"18,765",...,14.1,"24,439",0.2,"29,351",0.3,"220,878",2.2,50.0,37.0,NaN
1,Riverside County,70,"2,323,892","1,102,968",47.5,"865,631",37.2,"137,779",5.9,"9,407",...,6.0,"6,262",0.3,"3,749",0.2,"58,988",2.5,50.0,65.0,NaN
2,San Diego County,61,"3,253,356","1,076,319",33.1,"1,519,704",46.7,"154,251",4.7,"11,833",...,11.3,"14,043",0.4,"5,543",0.2,"102,611",3.2,50.0,73.0,NaN
3,San Bernardino County,60,"2,106,754","1,089,104",51.7,"642,786",30.5,"170,376",8.1,"6,840",...,6.6,"6,368",0.3,"4,417",0.2,"48,112",2.3,50.0,71.0,NaN
4,Alameda County,48,"1,605,217","362,070",22.6,"523,797",32.6,"176,819",11.0,"4,959",...,28.0,"13,223",0.8,"4,524",0.3,"70,149",4.4,50.0,1.0,NaN

In [146]:
# save to csv 
merged_df.to_csv('ca_county_pd_incidents_and_demographics.csv', encoding='utf-8', index=False)